//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        { }
        public  Customer(string customerName, string userName, string customerEmail, string password)
        {
            CustomerName = customerName;
            UserName = userName;
            CustomerEmail = customerName;
            Password = password;
        }
        public string CustomerName { get; set; }
        public string UserName { get; set; }
        public string CustomerEmail { get; set; }
        public string Password { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
