//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventManager
    {
        public EventManager()
        {
        }
        public EventManager(string managerName,string managerEmail, string password,string username)
        {
            ManagerName = managerName;
            ManagerEmail = managerEmail;
            Password = password;
            UserName = username;
        
        }
           

        
        
        public string ManagerName { get; set; }
        public string ManagerEmail { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
