//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class EventsAndDecoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsAndDecoration()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string EventType { get; set; }
        public string DecorationType { get; set; }
        public string DecorationImage { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public  HttpPostedFileBase ImageFile { get; set; }
    }
}
