//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projrct2EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string UserName { get; set; }
        public string Emailid { get; set; }
        public string CustomerFeedback { get; set; }
        public string Name { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
